package az.store.payment;

import az.store.Inits;
import az.store.types.CodeType;
import az.store.types.Report;
import az.util.components.ExcelWriter;
import az.util.components.ObjectTableModel;
import az.util.utils.Utils;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author Rashad Amirjanov
 */
public class PaymentsReportPanel extends javax.swing.JPanel {

    private Report reportTillFromDate = new Report();
    private Report reportBetweenDates = new Report();

    private class PaymentsTableModel extends ObjectTableModel {

        public PaymentsTableModel() {
            super(new String[]{"Tipi", "Tarix", "Məbləğ", "Qeyd"});//, "Məbləğ (valyuta ilə)"});
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Payment payment = (Payment) this.getRowObjects().get(rowIndex);

            Object result = null;
            switch (columnIndex) {
                case 0:
                    result = payment.getClient().getName();
                    break;
                case 1:
                    result = Utils.toStringDate(payment.getDateTime());
                    break;
                case 2:
                    result = payment.getSumma() + " (AZN)";
                    break;
                case 3:
                    result = payment.getDescr();
//                    result = payment.getCurrencySumma() + " (" + payment.getCurrencyType().getName() + ")";
                    break;
            }
            if (result == null) {
                result = "";
            }

            return result;
        }
    };
    PaymentsTableModel tableModelPostavsik = new PaymentsTableModel();
    PaymentsTableModel tableModelExpenditure = new PaymentsTableModel();
    PaymentsTableModel tableModelClient = new PaymentsTableModel();

    /**
     * Creates new form PaymentsReportPanel
     */
    public PaymentsReportPanel() {
        initComponents();

        jTblExpenditure.setModel(tableModelExpenditure);
        jTblClients.setModel(tableModelClient);
        jTblPostavsik.setModel(tableModelPostavsik);
        
        jlabelExpenditure.setVisible(false);
        jlabelFirstSum.setVisible(false);
        jlabelLastSum.setVisible(false);
        
        jlbExpenditure.setVisible(false);
        jlbFirstSum.setVisible(false);
        jlbLastSum.setVisible(false);
        
        jTabReports.remove(jScrollExpenditure);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlParameters = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnShowReport = new javax.swing.JButton();
        jDtToDate = new az.util.components.JDateChooserEx();
        jDtFromDate = new az.util.components.JDateChooserEx();
        jPanel1 = new javax.swing.JPanel();
        jlabelExpenditure = new javax.swing.JLabel();
        jlbExpenditure = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblPostavsik = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLblClients = new javax.swing.JLabel();
        jlbLastSum = new javax.swing.JLabel();
        jlabelLastSum = new javax.swing.JLabel();
        jlabelFirstSum = new javax.swing.JLabel();
        jlbFirstSum = new javax.swing.JLabel();
        jTabReports = new javax.swing.JTabbedPane();
        jScrollExpenditure = new javax.swing.JScrollPane();
        jTblExpenditure = new javax.swing.JTable();
        jScrollPostavsik = new javax.swing.JScrollPane();
        jTblPostavsik = new javax.swing.JTable();
        jScrollClients = new javax.swing.JScrollPane();
        jTblClients = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jPnlParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Ödəniş üçün parametrlər"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tarixdən");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tarixə kimi");

        jBtnShowReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/Search.png"))); // NOI18N
        jBtnShowReport.setText("Göstər");
        jBtnShowReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShowReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlParametersLayout = new javax.swing.GroupLayout(jPnlParameters);
        jPnlParameters.setLayout(jPnlParametersLayout);
        jPnlParametersLayout.setHorizontalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jDtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnShowReport, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlParametersLayout.setVerticalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParametersLayout.createSequentialGroup()
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addComponent(jDtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnShowReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nəticə"));

        jlabelExpenditure.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlabelExpenditure.setText("Xərclərə gedən pullar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Məhsul gətirənlərə ödənişlər");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Satış məntəqələrinin ödənişləri");

        jlabelLastSum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlabelLastSum.setText("Son məbləğ");

        jlabelFirstSum.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlabelFirstSum.setText("İlkin məbləğ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelLastSum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelFirstSum, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbFirstSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbExpenditure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblPostavsik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbLastSum, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelFirstSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbFirstSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelExpenditure)
                    .addComponent(jlbExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLblPostavsik, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblClients, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelLastSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbLastSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        jTblExpenditure.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollExpenditure.setViewportView(jTblExpenditure);

        jTabReports.addTab("Xərclərə gedən pullar", jScrollExpenditure);

        jTblPostavsik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPostavsik.setViewportView(jTblPostavsik);

        jTabReports.addTab("Məhsul gətirənlərə ödənişlər", jScrollPostavsik);

        jTblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollClients.setViewportView(jTblClients);

        jTabReports.addTab("Satış məntəqələrinin ödənişləri", jScrollClients);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/excel.png"))); // NOI18N
        jButton3.setText("Exceldə göstər");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabReports, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnlParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabReports, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnShowReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShowReportActionPerformed
        jLblClients.setText("");
        jlbExpenditure.setText("");
        jLblPostavsik.setText("");
        jlbFirstSum.setText("");
        jlbLastSum.setText("");
        tableModelClient.removeAll();
        tableModelExpenditure.removeAll();
        tableModelPostavsik.removeAll();

        Date dateFrom = jDtFromDate.getDate();
        Date dateTo = jDtToDate.getDate();

        if (dateTo == null || dateFrom == null) {
            JOptionPane.showMessageDialog(this, "Xahiş olunur məlumatları tam daxil edin!");
            return;
        }

        {//reportsBetweenDates
            reportBetweenDates.setFromDate(dateFrom);
            reportBetweenDates.setToDate(dateTo);

//            reportBetweenDates.setFirstSumma(reportTillFromDate.getLastSumma());
//        reportBetweenDates.setFromDate(dateFrom);
//            dateFrom = reportBetweenDates.getFromDate();
            double sumPostavsik = Inits.getSelectQueries().getPaymentsSum(CodeType.POSTAVSIK, dateFrom, dateTo);
            double sumClient = Inits.getSelectQueries().getPaymentsSum(CodeType.CLIENTS, dateFrom, dateTo);
            double sumExpenditure = Inits.getSelectQueries().getPaymentsSum(CodeType.EXPENDITURES, dateFrom, dateTo);

            ArrayList<Payment> paymentsPostavsik = Inits.getSelectQueries().getPayments(dateFrom, dateTo, CodeType.POSTAVSIK, null);
            ArrayList<Payment> paymentsClients = Inits.getSelectQueries().getPayments(dateFrom, dateTo, CodeType.CLIENTS, null);
            ArrayList<Payment> paymentsExpenditure = Inits.getSelectQueries().getPayments(dateFrom, dateTo, CodeType.EXPENDITURES, null);

            reportBetweenDates.setPostavsik(sumPostavsik);
            reportBetweenDates.setClient(sumClient);
            reportBetweenDates.setExpenditure(sumExpenditure);
            System.out.println(reportBetweenDates.getFirstSumma());
            System.out.println(reportBetweenDates.getClient());
            System.out.println(reportBetweenDates.getExpenditure());
            System.out.println(reportBetweenDates.getPostavsik());
//            reportBetweenDates.setLastSumma(reportBetweenDates.getFirstSumma() + reportBetweenDates.getClient()
//                    - reportBetweenDates.getExpenditure() - reportBetweenDates.getPostavsik());

            System.out.println("reportBetweenDates last summa =" + reportBetweenDates.getLastSumma());

            jlbFirstSum.setText(reportBetweenDates.getFirstSumma() + " (AZN)");
            jlbExpenditure.setText(String.valueOf(sumExpenditure) + " (AZN)");
            jLblClients.setText(String.valueOf(sumClient) + " (AZN)");
            jLblPostavsik.setText(String.valueOf(sumPostavsik) + " (AZN)");
            jlbLastSum.setText(reportBetweenDates.getLastSumma() + " (AZN)");

            tableModelPostavsik.removeAll();
            for (Payment payment : paymentsPostavsik) {
                tableModelPostavsik.addObject(payment);
            }

            tableModelClient.removeAll();
            for (Payment payment : paymentsClients) {
                tableModelClient.addObject(payment);
            }

            tableModelExpenditure.removeAll();
            for (Payment payment : paymentsExpenditure) {
                tableModelExpenditure.addObject(payment);
            }
        }

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dateFrom);
        calendar.set(Calendar.DAY_OF_MONTH, calendar.get(Calendar.DAY_OF_MONTH) - 1);
        reportTillFromDate.setToDate(calendar.getTime());
        reportTillFromDate.setFromDate(dateFrom);

        double sumPostavsik = Inits.getSelectQueries().getPaymentsSum(CodeType.POSTAVSIK, reportTillFromDate.getFromDate(), reportTillFromDate.getToDate());
        double sumClient = Inits.getSelectQueries().getPaymentsSum(CodeType.CLIENTS, reportTillFromDate.getFromDate(), reportTillFromDate.getToDate());
        double sumExpenditure = Inits.getSelectQueries().getPaymentsSum(CodeType.EXPENDITURES, reportTillFromDate.getFromDate(), reportTillFromDate.getToDate());

        reportTillFromDate.setPostavsik(sumPostavsik);
        reportTillFromDate.setClient(sumClient);
        reportTillFromDate.setExpenditure(sumExpenditure);
//        reportTillFromDate.setLastSumma(reportTillFromDate.getFirstSumma() + reportTillFromDate.getClient()
//                - reportTillFromDate.getExpenditure() - reportTillFromDate.getPostavsik());
        System.out.println("reportTillFromDate last summa =" + reportTillFromDate.getLastSumma());


    }//GEN-LAST:event_jBtnShowReportActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            ExcelWriter.viewAsExcelFile(new ObjectTableModel[]{
                tableModelExpenditure, tableModelPostavsik, tableModelClient
            }, new String[]{
                "Xərclərə gedən pullar", "Məhsul gətirənlərə gedən pullar", "Klientlərdən gələn pullar"
            });
        } catch (IOException | WriteException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void showForm() {
        clearParameters();

//        refreshCurrentReport();
//        setTitle("Hesabat");

//        setVisible(true);
    }

//    private void refreshCurrentReport() {
//        tableModelExpenditure.removeAll();
//        tableModelClient.removeAll();
//        tableModelPostavsik.removeAll();
//
//        ArrayList<Report> reports = Inits.getSelectQueries().getCurrentReport();
//        if (reports.size() > 0) {
//            Report report = reports.get(0);
//
//            reportTillFromDate = report;
//
////            jLblFromDate.setText(Initialization.DATE_FORMAT.format(report.getFromDate()));
//            jDtToDate.setMinSelectableDate(report.getFromDate());
////            jLblSumma.setText(String.valueOf(report.getFirstSumma()));
//        } else {
////            jLblFromDate.setText("");
////            jLblSumma.setText("");
//        }
//    }

//    private void refreshPayments() {
//        tableModelPayments.removeAll();
////
////        CodeValue codeValue = (CodeValue) jCbCodeValue.getSelectedItem();
////        if (codeValue == null) {
//////            System.out.println("code value is null");
////            return;
////        }
////
////        ArrayList<VPayment> payments = Initialization.getSelectQueries().getPaymentsByCodeValue(codeValue);
////        for (Payment payment : payments) {
////            tableModelPayments.addObject(payment);
////        }
//
//    }
    private void clearParameters() {
        jDtFromDate.setDate(new Date());
        jDtToDate.setDate(new Date());
//        jLblFromDate.setText("");
//        jLblSumma.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnShowReport;
    private javax.swing.JButton jButton3;
    private az.util.components.JDateChooserEx jDtFromDate;
    private az.util.components.JDateChooserEx jDtToDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblClients;
    private javax.swing.JLabel jLblPostavsik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlParameters;
    private javax.swing.JScrollPane jScrollClients;
    private javax.swing.JScrollPane jScrollExpenditure;
    private javax.swing.JScrollPane jScrollPostavsik;
    private javax.swing.JTabbedPane jTabReports;
    private javax.swing.JTable jTblClients;
    private javax.swing.JTable jTblExpenditure;
    private javax.swing.JTable jTblPostavsik;
    private javax.swing.JLabel jlabelExpenditure;
    private javax.swing.JLabel jlabelFirstSum;
    private javax.swing.JLabel jlabelLastSum;
    private javax.swing.JLabel jlbExpenditure;
    private javax.swing.JLabel jlbFirstSum;
    private javax.swing.JLabel jlbLastSum;
    // End of variables declaration//GEN-END:variables
}
