package az.store.main;

import az.util.components.document.JTextFieldOnlyNumber;
import az.util.utils.Utils;

import javax.swing.*;

/**
 * @author EMIL_MSI
 */
public class CurrencyDialog extends javax.swing.JDialog {

    private Double currency = null;
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAccept;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblPriceByCurrencyCaption;
    private javax.swing.JLabel jLblPriceReal;
    private javax.swing.JLabel jLblPriceSale;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtPriceByCurrency;
    private javax.swing.JLabel jlblPriceBuy;

    /**
     * Creates new form CurrencyDialog
     */
    public CurrencyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTxtPriceByCurrency.setDocument(new JTextFieldOnlyNumber());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlblPriceBuy = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLblPriceSale = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLblPriceReal = new javax.swing.JLabel();
        jLblPriceByCurrencyCaption = new javax.swing.JLabel();
        jTxtPriceByCurrency = new javax.swing.JTextField();
        jBtnAccept = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();

        setTitle("Valyuta ilə");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Alış qiməti ilə");
        jPanel1.add(jLabel1);

        jlblPriceBuy.setText("jlblPriceBuy");
        jPanel1.add(jlblPriceBuy);

        jLabel3.setText("Satış qiməti ilə");
        jPanel1.add(jLabel3);

        jLblPriceSale.setText("jLblPriceSale");
        jPanel1.add(jLblPriceSale);

        jLabel4.setText("Real qiyməti ilə");
        jPanel1.add(jLabel4);

        jLblPriceReal.setText("jLblPriceReal");
        jPanel1.add(jLblPriceReal);

        jLblPriceByCurrencyCaption.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblPriceByCurrencyCaption.setText("Alış qiməti digər valuta ilə");
        jPanel1.add(jLblPriceByCurrencyCaption);

        jTxtPriceByCurrency.setText("jTxtPriceByCurrency");
        jPanel1.add(jTxtPriceByCurrency);

        jBtnAccept.setText("Qəbul et");
        jBtnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAcceptActionPerformed(evt);
            }
        });

        jBtnCancel.setText("İmtina et");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jBtnAccept)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBtnCancel)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtnAccept)
                                        .addComponent(jBtnCancel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Double showForm(Double[] results, String text) {
        currency = null;
        jlblPriceBuy.setText(null);
        jLblPriceSale.setText(null);
        jLblPriceReal.setText(null);
        jTxtPriceByCurrency.setText(null);
        jLblPriceByCurrencyCaption.setText(text);

        jlblPriceBuy.setText(Utils.toString(results[0]));
        jLblPriceSale.setText(Utils.toString(results[1]));
        jLblPriceReal.setText(Utils.toString(results[2]));
        this.setVisible(true);
        return currency;

    }

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        currency = null;
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAcceptActionPerformed
        if (jTxtPriceByCurrency.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Xahiş olunur məlumatları tam daxil edin!");
            return;
        }
        try {
            currency = (Double.parseDouble(jTxtPriceByCurrency.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Məbləği götürə bilmədi");
            return;
        }
        this.setVisible(false);
    }//GEN-LAST:event_jBtnAcceptActionPerformed
    // End of variables declaration//GEN-END:variables
}
