package az.store.report;

import az.store.Inits;
import az.store.invoice.InvoiceType;
import az.store.types.CodeType;
import az.store.types.CodeValue;
import az.util.components.ExcelWriter;
import az.util.components.ObjectTableModel;
import az.util.utils.Utils;
import java.awt.Component;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jxl.write.WriteException;

/**
 *
 * @author Rashad Amirjanov
 */
public class ProductReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductReportPanel
     */
    private ObjectTableModel tmReports = new ObjectTableModel(new String[]{
        "", "", "", ""
    }) {

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object[] hesab = (Object[]) this.getRowObjects().get(rowIndex);

            Object result = hesab[columnIndex];

            if (result == null) {
                result = "";
            }

            return result;
        }
    };

    public ProductReportPanel() {
        initComponents();
        jtbResult.setModel(tmReports);
        setDatesEnable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbResult = new javax.swing.JTable();
        jPnlParameters = new javax.swing.JPanel();
        jbtnShowReport = new javax.swing.JButton();
        jbtnExcel = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        cbFilterType = new javax.swing.JComboBox<>();
        jpnlDates = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdtFromDate = new az.util.components.JDateChooserEx();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jdtToDate = new az.util.components.JDateChooserEx();

        setLayout(new java.awt.BorderLayout());

        jtbResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbResult);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPnlParameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jbtnShowReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/Search.png"))); // NOI18N
        jbtnShowReport.setText("Göstər");
        jbtnShowReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowReportActionPerformed(evt);
            }
        });

        jbtnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/excel.png"))); // NOI18N
        jbtnExcel.setText("Çapa ver");
        jbtnExcel.setPreferredSize(new java.awt.Dimension(110, 25));
        jbtnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcelActionPerformed(evt);
            }
        });

        jbtnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/DeleteRed.png"))); // NOI18N
        jbtnClear.setText("Təmizlə");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        cbFilterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ümumi dövriyyə", "İnterval üzrə dövriyyə" }));
        cbFilterType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilterTypeItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tarixdən");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tarixə kimi");

        javax.swing.GroupLayout jpnlDatesLayout = new javax.swing.GroupLayout(jpnlDates);
        jpnlDates.setLayout(jpnlDatesLayout);
        jpnlDatesLayout.setHorizontalGroup(
            jpnlDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jdtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlDatesLayout.setVerticalGroup(
            jpnlDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdtFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jdtToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jpnlDatesLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jpnlDatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)))
        );

        javax.swing.GroupLayout jPnlParametersLayout = new javax.swing.GroupLayout(jPnlParameters);
        jPnlParameters.setLayout(jPnlParametersLayout);
        jPnlParametersLayout.setHorizontalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlParametersLayout.createSequentialGroup()
                        .addComponent(cbFilterType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnlDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPnlParametersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnShowReport, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jbtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnlParametersLayout.setVerticalGroup(
            jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlParametersLayout.createSequentialGroup()
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnShowReport)
                    .addComponent(cbFilterType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlDates, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnClear)
                    .addComponent(jbtnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPnlParameters, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShowReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShowReportActionPerformed
        tmReports.removeAll();
        Date dateFrom = jdtFromDate.getDate();
        Date dateTo = jdtToDate.getDate();

        if (dateFrom == null || dateTo == null) {
            JOptionPane.showMessageDialog(null, "Tarixi daxil edin.");
            return;
        }

        tmReports.addObject(new Object[]{
            "Tarix", Utils.toStringDate(dateFrom), Utils.toStringDate(dateTo), ""
        });
        tmReports.addObject(new Object[]{
            "", "", "", ""
        });
        tmReports.addObject(new Object[]{
            "", "Alış qiyməti", "Satış qiyməti", ""
        });

        double debt = 0;

        ArrayList<InvoiceType> invoiceTypes = Inits.getSelectQueries().getAllInvoiceTypes();
        for (InvoiceType invoiceType : invoiceTypes) {
            if (invoiceType.getClientCodeType().equals(CodeType.ESTIMATE)) {
                continue;//qaliq mehsul borc hesablanmasinda nezere alinmir
            }
            Double[] dd = Inits.getSelectQueries().getInvoicesSums(null, dateFrom, dateTo, invoiceType);
            double d = (dd[1] != 0) ? dd[1] : dd[0];
            tmReports.addObject(new Object[]{
                invoiceType.getName(), Utils.toString(dd[0]), Utils.toString(dd[1]), "" //Utils.toString(invoiceType.getSign() * d)
            });

            debt += -1 * invoiceType.getSign() * d;
        }

        tmReports.addObject(new Object[]{
            "", "", "", ""
        });
        //currentstoredaki mehsulu hesabla
//        Double[] dd = Inits.getSelectQueries().getCurrentStoreSums(CodeValue.PST_PRODUCTION_PRODUCT);
//        tmReports.addObject(new Object[]{
//            "Cari anda anbarda [Hazır məhsul]", dd[0], dd[1], ""
//        });
//        Double[] dd2 = Inits.getSelectQueries().getCurrentStoreSums(CodeValue.PST_SIMPLE_PRODUCT);
//        tmReports.addObject(new Object[]{
//            "Cari anda anbarda [Sadə məhsul]", dd2[0], dd2[1], ""
//        });
//        tmReports.addObject(new Object[]{
//            "", "", "", ""
//        });

//        double sumPostavsik = Inits.getSelectQueries().getPaymentsSum(CodeType.POSTAVSIK, dateFrom, dateTo);
//        double sumExpenditure = Inits.getSelectQueries().getPaymentsSum(CodeType.EXPENDITURES, dateFrom, dateTo);
        double sumClient = Inits.getSelectQueries().getPaymentsSum(CodeType.CLIENTS, dateFrom, dateTo);

//        tmReports.addObject(new Object[]{
//            "Məhsul gətirənlərə ödənişlər", sumPostavsik, "", "" //+1 * sumPostavsik
//        });
//        tmReports.addObject(new Object[]{
//            "Xərclər", sumExpenditure, "", ""
//        });
        tmReports.addObject(new Object[]{
            "Müştərilərin ödənişləri", sumClient, "", "" //-1 * sumClient
        });

        debt += -sumClient;
        debt = -1 * debt;

        tmReports.addObject(new Object[]{
            "", "", "", ""
        });

        tmReports.addObject(new Object[]{
            "Müştəriyə olan borc", Utils.toString(debt), "", ""
        });

    }//GEN-LAST:event_jbtnShowReportActionPerformed

    private void jbtnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcelActionPerformed
        try {
            ExcelWriter.viewAsExcelFile(new ObjectTableModel[]{tmReports},
                    new String[]{
                        "Umumi"
                    });
        } catch (IOException | WriteException ex) {
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnExcelActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        tmReports.removeAll();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void cbFilterTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilterTypeItemStateChanged
        boolean enabled = cbFilterType.getSelectedIndex() == 1;
        setDatesEnable(enabled);
    }//GEN-LAST:event_cbFilterTypeItemStateChanged

    void setDatesEnable(boolean enabled) {
        jpnlDates.setEnabled(enabled);
        for (Component component : jpnlDates.getComponents()) {
            component.setEnabled(enabled);
        }
        try {
            if (enabled) {
                jdtFromDate.setDate(new Date());
                jdtToDate.setDate(new Date());
            } else {
                jdtFromDate.setDate(Utils.DATE_FORMAT.parse("01.01.2010"));
                jdtToDate.setDate(Utils.DATE_FORMAT.parse("01.01.2050"));
            }
        } catch (ParseException ex) {
            Logger.getLogger(ProductReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void showForm() {
        tmReports.removeAll();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbFilterType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPnlParameters;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnExcel;
    private javax.swing.JButton jbtnShowReport;
    private az.util.components.JDateChooserEx jdtFromDate;
    private az.util.components.JDateChooserEx jdtToDate;
    private javax.swing.JPanel jpnlDates;
    private javax.swing.JTable jtbResult;
    // End of variables declaration//GEN-END:variables
}
