package az.store.report;

/**
 *
 * @author Rashad Amirjanov
 */
public class ReportDialog extends javax.swing.JDialog {

    private static ReportDialog reportDialog = null;

    public static ReportDialog instance() {
        if (reportDialog == null) {
            reportDialog = new ReportDialog(null, true);
        }
        return reportDialog;
    }

    /**
     * Creates new form ReportDialog
     */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        jTabbedPane1.remove(jtabPostavsikAndClient);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jtabPaymentsReport = new az.store.payment.PaymentsReportPanel();
        jtabPostavsikAndClient = new az.store.report.PostavsikAndClientPanel();
        jtabProductReport = new az.store.report.ProductReportPanel();
        jbtClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addTab("Ödənişlərin hesabatı", jtabPaymentsReport);
        jTabbedPane1.addTab("Məhsul gətirən və Satış məntəqələrinin hesabatı", jtabPostavsikAndClient);
        jTabbedPane1.addTab("Dövriyyə hesabatı", jtabProductReport);

        jbtClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/az/store/images/close.png"))); // NOI18N
        jbtClose.setText("Bağla");
        jbtClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jbtCloseActionPerformed

    public void showForm(int tabIndex) {
        jTabbedPane1.setSelectedIndex(tabIndex);
        jtabPaymentsReport.showForm();
        jtabPostavsikAndClient.showForm();
        jtabProductReport.showForm();

        setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtClose;
    private az.store.payment.PaymentsReportPanel jtabPaymentsReport;
    private az.store.report.PostavsikAndClientPanel jtabPostavsikAndClient;
    private az.store.report.ProductReportPanel jtabProductReport;
    // End of variables declaration//GEN-END:variables
}
